import asyncio
import json
import os
import sys
from datetime import datetime

# スクリプトのディレクトリを取得
script_dir = os.path.dirname(os.path.abspath(__file__))

# プロジェクトのルートディレクトリ（appの3つ上）をパスに追加
project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
if project_root not in sys.path:
    sys.path.append(project_root)

from app.translation.openai_service import openai_service
from app.core.logging import get_logger

logger = get_logger(__name__)

async def test_summary():
    # 1. モックデータの読み込み (同じフォルダにある)
    mock_file_path = os.path.join(script_dir, "mock_stt_data.json")
    
    if not os.path.exists(mock_file_path):
        print(f"Error: {mock_file_path} not found.")
        return

    with open(mock_file_path, "r", encoding="utf-8") as f:
        mock_data = json.load(f)

    # room_1 のデータを使用
    room_id = "room_1"
    if room_id not in mock_data:
        print(f"Error: {room_id} not found in mock data.")
        return

    data = mock_data[room_id]
    members = data.get("members", [])
    stt_results = data.get("stt_results", [])
    
    participant_names = [m["display_name"] for m in members]
    member_map = {m["id"]: m["display_name"] for m in members}

    # 2. プロンプトの構築
    text_parts = ["=== VOICE TRANSCRIPT (Speech-to-Text) ==="]
    for msg in stt_results:
        sender_name = member_map.get(msg["member_id"], "Unknown")
        time_str = datetime.fromisoformat(msg["created_at"]).strftime('%H:%M:%S')
        seq = msg["seq"]
        text_parts.append(f"[{time_str}] [{seq}] {sender_name}: {msg['stt_text']}")
    
    conversation_text = "\n".join(text_parts)

    prompt = f"""
You are a professional meeting summarizer specializing in analyzing voice transcriptions from meetings.

The following is a transcript of a meeting generated by speech-to-text (STT) technology. 
The transcript is presented in chronological order with timestamps.

Note: As this is STT output, there may be:
- Minor transcription errors
- Informal spoken language
- Incomplete sentences or fillers (um, uh, etc.)

Your task is to analyze the conversation flow and extract meaningful information.

Voice Transcript:
{conversation_text}

Participants: {', '.join(participant_names)}

Please provide a comprehensive summary with:

1. **Main Points**: What were the key topics discussed during the meeting? Summarize the main ideas and important discussions in a clear, organized manner.

2. **Tasks/Action Items**: What specific actions or tasks were mentioned? Who is responsible for each task? Include any deadlines or timeframes mentioned.

3. **Decisions**: What key decisions were made? What agreements or conclusions were reached during the meeting?

Respond ONLY with valid JSON in this exact format:
{{
    "main_point": "Clear and comprehensive summary of the main discussion topics",
    "task": "List of action items with responsible persons and deadlines",
    "decided": "Key decisions and agreements made during the meeting"
}}
"""

    print("--- Generated Prompt ---")
    print(prompt)
    print("------------------------")

    # 3. OpenAI 呼び出し
    if not openai_service.client:
        print("Error: OpenAI API key is not configured.")
        return

    print("Sending request to OpenAI...")
    try:
        response = openai_service.client.chat.completions.create(
            model=openai_service.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are a professional meeting summarizer specializing in voice transcriptions. You provide comprehensive, concise summaries in valid JSON format. IMPORTANT: Always provide the summarization content in Japanese."
                },
                {"role": "user", "content": f"{prompt}\n\nPlease output the 'main_point', 'task', and 'decided' fields in Japanese."}
            ],
            response_format={"type": "json_object"},
        )
        
        result = json.loads(response.choices[0].message.content)
        print("\n--- Summary Result ---")
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("-----------------------")
        
    except Exception as e:
        print(f"Error during OpenAI call: {e}")

if __name__ == "__main__":
    asyncio.run(test_summary())
