"""
Summary Model

Stores meeting summaries generated by AI.
"""

from typing import Optional

from sqlalchemy import String, Integer, ForeignKey, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Summary(Base, TimestampMixin):
    __tablename__ = "summaries"

    id: Mapped[int] = mapped_column(primary_key=True)
    meeting_id: Mapped[int] = mapped_column(ForeignKey("meetings.id"), index=True)
    
    # Structured summary content
    content_text: Mapped[str] = mapped_column(Text)  # Full summary text
    
    # JSON structured data
    decisions: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    action_items: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    risks: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    
    # Metadata
    model_used: Mapped[str] = mapped_column(String(50), nullable=True)
    
    # Relationships
    meeting: Mapped["Meeting"] = relationship(back_populates="summaries")
